# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
  
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Generate .env file
      run:  |
        echo ${{ secrets.REACT_APP_SCRIPT_URL }}
        echo ${{ secrets.REACT_APP_SCRIPT_URL }} > .env
        cat .env
      shell: bash
    
    - name: setup git config
      run: |
        git config user.name "denisenanni"
        git config user.email "info@devdenise.com"
        
    - name: Install dependencies
      run: npm install

    - name: Run the tests
      run: npm test

    - name: Build
      run: npm run build
    
    - name: Deploy your app to GitHub Pages
      uses: awb-pw/deploy-to-github-pages-action@1.1.1
    
      # git config --list
      # git remote set-url origin https://git:${PA_TOKEN}@github.com/${GITHUB_PAGE_NAME}.git
      env:
          AUTHOR: denisenanni
          BUILD_PATH: build
          GITHUB_PAGE_NAME: pubbliufficio
          PA_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          SCRIPT_URL: ${{ secrets.SCRIPT_URL }}
